/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 35
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_DEPLOYMENT_DASHID = 1,
  anon_sym_VERSION_DASHID = 2,
  anon_sym_ENVIRONMENTSECTION = 3,
  anon_sym_SERVICESSECTION = 4,
  anon_sym_SERVICE = 5,
  anon_sym_END = 6,
  anon_sym_IMAGE_DASHID = 7,
  anon_sym_PORT_DASHMAPPING = 8,
  anon_sym_ENV_DASHVARIABLE = 9,
  anon_sym_COMMAND = 10,
  anon_sym_DEPENDS_DASHON = 11,
  anon_sym_HEALTH_DASHCHECK = 12,
  anon_sym_RESTART_DASHPOLICY = 13,
  anon_sym_RESOURCE_DASHLIMITS = 14,
  anon_sym_CPU = 15,
  anon_sym_MEMORY = 16,
  anon_sym_VOLUME_DASHMAPPING = 17,
  anon_sym_TO = 18,
  anon_sym_NETWORK_DASHNAME = 19,
  sym_template_var = 20,
  sym_quoted_string = 21,
  anon_sym_always = 22,
  anon_sym_unless_DASHstopped = 23,
  anon_sym_on_DASHfailure = 24,
  sym_identifier = 25,
  sym_version = 26,
  sym_number = 27,
  sym_value = 28,
  sym_comment = 29,
  sym_empty_line = 30,
  sym_source_file = 31,
  sym_line = 32,
  sym_deployment_directive = 33,
  sym_version_directive = 34,
  sym_section_directive = 35,
  sym_service_directive = 36,
  sym_end_service = 37,
  sym_service_property = 38,
  sym_port_mapping = 39,
  sym_restart_policy = 40,
  aux_sym_source_file_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DEPLOYMENT_DASHID] = "DEPLOYMENT-ID",
  [anon_sym_VERSION_DASHID] = "VERSION-ID",
  [anon_sym_ENVIRONMENTSECTION] = "ENVIRONMENT SECTION",
  [anon_sym_SERVICESSECTION] = "SERVICES SECTION",
  [anon_sym_SERVICE] = "SERVICE",
  [anon_sym_END] = "END",
  [anon_sym_IMAGE_DASHID] = "IMAGE-ID",
  [anon_sym_PORT_DASHMAPPING] = "PORT-MAPPING",
  [anon_sym_ENV_DASHVARIABLE] = "ENV-VARIABLE",
  [anon_sym_COMMAND] = "COMMAND",
  [anon_sym_DEPENDS_DASHON] = "DEPENDS-ON",
  [anon_sym_HEALTH_DASHCHECK] = "HEALTH-CHECK",
  [anon_sym_RESTART_DASHPOLICY] = "RESTART-POLICY",
  [anon_sym_RESOURCE_DASHLIMITS] = "RESOURCE-LIMITS",
  [anon_sym_CPU] = "CPU",
  [anon_sym_MEMORY] = "MEMORY",
  [anon_sym_VOLUME_DASHMAPPING] = "VOLUME-MAPPING",
  [anon_sym_TO] = "TO",
  [anon_sym_NETWORK_DASHNAME] = "NETWORK-NAME",
  [sym_template_var] = "template_var",
  [sym_quoted_string] = "quoted_string",
  [anon_sym_always] = "always",
  [anon_sym_unless_DASHstopped] = "unless-stopped",
  [anon_sym_on_DASHfailure] = "on-failure",
  [sym_identifier] = "identifier",
  [sym_version] = "version",
  [sym_number] = "number",
  [sym_value] = "value",
  [sym_comment] = "comment",
  [sym_empty_line] = "empty_line",
  [sym_source_file] = "source_file",
  [sym_line] = "line",
  [sym_deployment_directive] = "deployment_directive",
  [sym_version_directive] = "version_directive",
  [sym_section_directive] = "section_directive",
  [sym_service_directive] = "service_directive",
  [sym_end_service] = "end_service",
  [sym_service_property] = "service_property",
  [sym_port_mapping] = "port_mapping",
  [sym_restart_policy] = "restart_policy",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DEPLOYMENT_DASHID] = anon_sym_DEPLOYMENT_DASHID,
  [anon_sym_VERSION_DASHID] = anon_sym_VERSION_DASHID,
  [anon_sym_ENVIRONMENTSECTION] = anon_sym_ENVIRONMENTSECTION,
  [anon_sym_SERVICESSECTION] = anon_sym_SERVICESSECTION,
  [anon_sym_SERVICE] = anon_sym_SERVICE,
  [anon_sym_END] = anon_sym_END,
  [anon_sym_IMAGE_DASHID] = anon_sym_IMAGE_DASHID,
  [anon_sym_PORT_DASHMAPPING] = anon_sym_PORT_DASHMAPPING,
  [anon_sym_ENV_DASHVARIABLE] = anon_sym_ENV_DASHVARIABLE,
  [anon_sym_COMMAND] = anon_sym_COMMAND,
  [anon_sym_DEPENDS_DASHON] = anon_sym_DEPENDS_DASHON,
  [anon_sym_HEALTH_DASHCHECK] = anon_sym_HEALTH_DASHCHECK,
  [anon_sym_RESTART_DASHPOLICY] = anon_sym_RESTART_DASHPOLICY,
  [anon_sym_RESOURCE_DASHLIMITS] = anon_sym_RESOURCE_DASHLIMITS,
  [anon_sym_CPU] = anon_sym_CPU,
  [anon_sym_MEMORY] = anon_sym_MEMORY,
  [anon_sym_VOLUME_DASHMAPPING] = anon_sym_VOLUME_DASHMAPPING,
  [anon_sym_TO] = anon_sym_TO,
  [anon_sym_NETWORK_DASHNAME] = anon_sym_NETWORK_DASHNAME,
  [sym_template_var] = sym_template_var,
  [sym_quoted_string] = sym_quoted_string,
  [anon_sym_always] = anon_sym_always,
  [anon_sym_unless_DASHstopped] = anon_sym_unless_DASHstopped,
  [anon_sym_on_DASHfailure] = anon_sym_on_DASHfailure,
  [sym_identifier] = sym_identifier,
  [sym_version] = sym_version,
  [sym_number] = sym_number,
  [sym_value] = sym_value,
  [sym_comment] = sym_comment,
  [sym_empty_line] = sym_empty_line,
  [sym_source_file] = sym_source_file,
  [sym_line] = sym_line,
  [sym_deployment_directive] = sym_deployment_directive,
  [sym_version_directive] = sym_version_directive,
  [sym_section_directive] = sym_section_directive,
  [sym_service_directive] = sym_service_directive,
  [sym_end_service] = sym_end_service,
  [sym_service_property] = sym_service_property,
  [sym_port_mapping] = sym_port_mapping,
  [sym_restart_policy] = sym_restart_policy,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DEPLOYMENT_DASHID] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_VERSION_DASHID] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ENVIRONMENTSECTION] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SERVICESSECTION] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SERVICE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_IMAGE_DASHID] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PORT_DASHMAPPING] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ENV_DASHVARIABLE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMAND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DEPENDS_DASHON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_HEALTH_DASHCHECK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RESTART_DASHPOLICY] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RESOURCE_DASHLIMITS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CPU] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MEMORY] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_VOLUME_DASHMAPPING] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TO] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NETWORK_DASHNAME] = {
    .visible = true,
    .named = false,
  },
  [sym_template_var] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_always] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unless_DASHstopped] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_on_DASHfailure] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_line] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_deployment_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_version_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_section_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_service_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_end_service] = {
    .visible = true,
    .named = true,
  },
  [sym_service_property] = {
    .visible = true,
    .named = true,
  },
  [sym_port_mapping] = {
    .visible = true,
    .named = true,
  },
  [sym_restart_policy] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(203);
      ADVANCE_MAP(
        '"', 3,
        '/', 19,
        'C', 118,
        'D', 44,
        'E', 102,
        'H', 45,
        'I', 91,
        'M', 54,
        'N', 46,
        'P', 115,
        'R', 47,
        'S', 53,
        'T', 116,
        'V', 55,
        'a', 178,
        'o', 181,
        'u', 182,
        '{', 195,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(231);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(148);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(150);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(225);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(176);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(164);
      if (lookahead == 'I') ADVANCE(139);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(88);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(71);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(131);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(188);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(125);
      END_STATE();
    case 12:
      if (lookahead == '-') ADVANCE(111);
      END_STATE();
    case 13:
      if (lookahead == '-') ADVANCE(72);
      END_STATE();
    case 14:
      if (lookahead == '-') ADVANCE(93);
      END_STATE();
    case 15:
      if (lookahead == '-') ADVANCE(75);
      END_STATE();
    case 16:
      if (lookahead == '-') ADVANCE(101);
      END_STATE();
    case 17:
      if (lookahead == '.') ADVANCE(200);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == '.') ADVANCE(201);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      if (lookahead == '/') ADVANCE(234);
      END_STATE();
    case 20:
      if (lookahead == 'A') ADVANCE(67);
      END_STATE();
    case 21:
      if (lookahead == 'A') ADVANCE(29);
      END_STATE();
    case 22:
      if (lookahead == 'A') ADVANCE(129);
      END_STATE();
    case 23:
      if (lookahead == 'A') ADVANCE(87);
      END_STATE();
    case 24:
      if (lookahead == 'A') ADVANCE(108);
      END_STATE();
    case 25:
      if (lookahead == 'A') ADVANCE(140);
      END_STATE();
    case 26:
      if (lookahead == 'A') ADVANCE(98);
      END_STATE();
    case 27:
      if (lookahead == 'A') ADVANCE(142);
      END_STATE();
    case 28:
      if (lookahead == 'A') ADVANCE(133);
      END_STATE();
    case 29:
      if (lookahead == 'B') ADVANCE(89);
      END_STATE();
    case 30:
      if (lookahead == 'C') ADVANCE(69);
      END_STATE();
    case 31:
      if (lookahead == 'C') ADVANCE(84);
      END_STATE();
    case 32:
      if (lookahead == 'C') ADVANCE(168);
      END_STATE();
    case 33:
      if (lookahead == 'C') ADVANCE(156);
      END_STATE();
    case 34:
      if (lookahead == 'C') ADVANCE(48);
      END_STATE();
    case 35:
      if (lookahead == 'C') ADVANCE(61);
      END_STATE();
    case 36:
      if (lookahead == 'C') ADVANCE(51);
      END_STATE();
    case 37:
      if (lookahead == 'C') ADVANCE(157);
      END_STATE();
    case 38:
      if (lookahead == 'D') ADVANCE(210);
      if (lookahead == 'V') ADVANCE(5);
      END_STATE();
    case 39:
      if (lookahead == 'D') ADVANCE(214);
      END_STATE();
    case 40:
      if (lookahead == 'D') ADVANCE(211);
      END_STATE();
    case 41:
      if (lookahead == 'D') ADVANCE(205);
      END_STATE();
    case 42:
      if (lookahead == 'D') ADVANCE(204);
      END_STATE();
    case 43:
      if (lookahead == 'D') ADVANCE(147);
      END_STATE();
    case 44:
      if (lookahead == 'E') ADVANCE(128);
      END_STATE();
    case 45:
      if (lookahead == 'E') ADVANCE(23);
      END_STATE();
    case 46:
      if (lookahead == 'E') ADVANCE(151);
      END_STATE();
    case 47:
      if (lookahead == 'E') ADVANCE(144);
      END_STATE();
    case 48:
      if (lookahead == 'E') ADVANCE(209);
      END_STATE();
    case 49:
      if (lookahead == 'E') ADVANCE(213);
      END_STATE();
    case 50:
      if (lookahead == 'E') ADVANCE(223);
      END_STATE();
    case 51:
      if (lookahead == 'E') ADVANCE(208);
      END_STATE();
    case 52:
      if (lookahead == 'E') ADVANCE(103);
      if (lookahead == 'L') ADVANCE(117);
      END_STATE();
    case 53:
      if (lookahead == 'E') ADVANCE(134);
      END_STATE();
    case 54:
      if (lookahead == 'E') ADVANCE(100);
      END_STATE();
    case 55:
      if (lookahead == 'E') ADVANCE(137);
      if (lookahead == 'O') ADVANCE(86);
      END_STATE();
    case 56:
      if (lookahead == 'E') ADVANCE(8);
      END_STATE();
    case 57:
      if (lookahead == 'E') ADVANCE(31);
      END_STATE();
    case 58:
      if (lookahead == 'E') ADVANCE(33);
      END_STATE();
    case 59:
      if (lookahead == 'E') ADVANCE(112);
      END_STATE();
    case 60:
      if (lookahead == 'E') ADVANCE(110);
      END_STATE();
    case 61:
      if (lookahead == 'E') ADVANCE(7);
      END_STATE();
    case 62:
      if (lookahead == 'E') ADVANCE(143);
      END_STATE();
    case 63:
      if (lookahead == 'E') ADVANCE(16);
      END_STATE();
    case 64:
      if (lookahead == 'E') ADVANCE(37);
      END_STATE();
    case 65:
      if (lookahead == 'G') ADVANCE(212);
      END_STATE();
    case 66:
      if (lookahead == 'G') ADVANCE(221);
      END_STATE();
    case 67:
      if (lookahead == 'G') ADVANCE(56);
      END_STATE();
    case 68:
      if (lookahead == 'H') ADVANCE(6);
      END_STATE();
    case 69:
      if (lookahead == 'H') ADVANCE(57);
      END_STATE();
    case 70:
      if (lookahead == 'I') ADVANCE(34);
      END_STATE();
    case 71:
      if (lookahead == 'I') ADVANCE(40);
      END_STATE();
    case 72:
      if (lookahead == 'I') ADVANCE(41);
      END_STATE();
    case 73:
      if (lookahead == 'I') ADVANCE(94);
      END_STATE();
    case 74:
      if (lookahead == 'I') ADVANCE(121);
      END_STATE();
    case 75:
      if (lookahead == 'I') ADVANCE(42);
      END_STATE();
    case 76:
      if (lookahead == 'I') ADVANCE(32);
      END_STATE();
    case 77:
      if (lookahead == 'I') ADVANCE(154);
      END_STATE();
    case 78:
      if (lookahead == 'I') ADVANCE(21);
      END_STATE();
    case 79:
      if (lookahead == 'I') ADVANCE(107);
      END_STATE();
    case 80:
      if (lookahead == 'I') ADVANCE(109);
      END_STATE();
    case 81:
      if (lookahead == 'I') ADVANCE(126);
      END_STATE();
    case 82:
      if (lookahead == 'I') ADVANCE(36);
      END_STATE();
    case 83:
      if (lookahead == 'I') ADVANCE(127);
      END_STATE();
    case 84:
      if (lookahead == 'K') ADVANCE(216);
      END_STATE();
    case 85:
      if (lookahead == 'K') ADVANCE(12);
      END_STATE();
    case 86:
      if (lookahead == 'L') ADVANCE(161);
      END_STATE();
    case 87:
      if (lookahead == 'L') ADVANCE(152);
      END_STATE();
    case 88:
      if (lookahead == 'L') ADVANCE(73);
      END_STATE();
    case 89:
      if (lookahead == 'L') ADVANCE(49);
      END_STATE();
    case 90:
      if (lookahead == 'L') ADVANCE(76);
      END_STATE();
    case 91:
      if (lookahead == 'M') ADVANCE(20);
      END_STATE();
    case 92:
      if (lookahead == 'M') ADVANCE(24);
      END_STATE();
    case 93:
      if (lookahead == 'M') ADVANCE(22);
      END_STATE();
    case 94:
      if (lookahead == 'M') ADVANCE(77);
      END_STATE();
    case 95:
      if (lookahead == 'M') ADVANCE(63);
      END_STATE();
    case 96:
      if (lookahead == 'M') ADVANCE(59);
      END_STATE();
    case 97:
      if (lookahead == 'M') ADVANCE(60);
      END_STATE();
    case 98:
      if (lookahead == 'M') ADVANCE(50);
      END_STATE();
    case 99:
      if (lookahead == 'M') ADVANCE(92);
      END_STATE();
    case 100:
      if (lookahead == 'M') ADVANCE(122);
      END_STATE();
    case 101:
      if (lookahead == 'M') ADVANCE(28);
      END_STATE();
    case 102:
      if (lookahead == 'N') ADVANCE(38);
      END_STATE();
    case 103:
      if (lookahead == 'N') ADVANCE(43);
      END_STATE();
    case 104:
      if (lookahead == 'N') ADVANCE(215);
      END_STATE();
    case 105:
      if (lookahead == 'N') ADVANCE(207);
      END_STATE();
    case 106:
      if (lookahead == 'N') ADVANCE(206);
      END_STATE();
    case 107:
      if (lookahead == 'N') ADVANCE(65);
      END_STATE();
    case 108:
      if (lookahead == 'N') ADVANCE(39);
      END_STATE();
    case 109:
      if (lookahead == 'N') ADVANCE(66);
      END_STATE();
    case 110:
      if (lookahead == 'N') ADVANCE(159);
      END_STATE();
    case 111:
      if (lookahead == 'N') ADVANCE(26);
      END_STATE();
    case 112:
      if (lookahead == 'N') ADVANCE(158);
      END_STATE();
    case 113:
      if (lookahead == 'N') ADVANCE(97);
      END_STATE();
    case 114:
      if (lookahead == 'N') ADVANCE(13);
      END_STATE();
    case 115:
      if (lookahead == 'O') ADVANCE(136);
      END_STATE();
    case 116:
      if (lookahead == 'O') ADVANCE(222);
      END_STATE();
    case 117:
      if (lookahead == 'O') ADVANCE(169);
      END_STATE();
    case 118:
      if (lookahead == 'O') ADVANCE(99);
      if (lookahead == 'P') ADVANCE(160);
      END_STATE();
    case 119:
      if (lookahead == 'O') ADVANCE(162);
      if (lookahead == 'T') ADVANCE(27);
      END_STATE();
    case 120:
      if (lookahead == 'O') ADVANCE(113);
      END_STATE();
    case 121:
      if (lookahead == 'O') ADVANCE(114);
      END_STATE();
    case 122:
      if (lookahead == 'O') ADVANCE(138);
      END_STATE();
    case 123:
      if (lookahead == 'O') ADVANCE(90);
      END_STATE();
    case 124:
      if (lookahead == 'O') ADVANCE(135);
      END_STATE();
    case 125:
      if (lookahead == 'O') ADVANCE(104);
      END_STATE();
    case 126:
      if (lookahead == 'O') ADVANCE(105);
      END_STATE();
    case 127:
      if (lookahead == 'O') ADVANCE(106);
      END_STATE();
    case 128:
      if (lookahead == 'P') ADVANCE(52);
      END_STATE();
    case 129:
      if (lookahead == 'P') ADVANCE(130);
      END_STATE();
    case 130:
      if (lookahead == 'P') ADVANCE(79);
      END_STATE();
    case 131:
      if (lookahead == 'P') ADVANCE(123);
      END_STATE();
    case 132:
      if (lookahead == 'P') ADVANCE(80);
      END_STATE();
    case 133:
      if (lookahead == 'P') ADVANCE(132);
      END_STATE();
    case 134:
      if (lookahead == 'R') ADVANCE(163);
      END_STATE();
    case 135:
      if (lookahead == 'R') ADVANCE(85);
      END_STATE();
    case 136:
      if (lookahead == 'R') ADVANCE(153);
      END_STATE();
    case 137:
      if (lookahead == 'R') ADVANCE(146);
      END_STATE();
    case 138:
      if (lookahead == 'R') ADVANCE(167);
      END_STATE();
    case 139:
      if (lookahead == 'R') ADVANCE(120);
      END_STATE();
    case 140:
      if (lookahead == 'R') ADVANCE(78);
      END_STATE();
    case 141:
      if (lookahead == 'R') ADVANCE(35);
      END_STATE();
    case 142:
      if (lookahead == 'R') ADVANCE(155);
      END_STATE();
    case 143:
      if (lookahead == 'R') ADVANCE(165);
      END_STATE();
    case 144:
      if (lookahead == 'S') ADVANCE(119);
      END_STATE();
    case 145:
      if (lookahead == 'S') ADVANCE(218);
      END_STATE();
    case 146:
      if (lookahead == 'S') ADVANCE(74);
      END_STATE();
    case 147:
      if (lookahead == 'S') ADVANCE(11);
      END_STATE();
    case 148:
      if (lookahead == 'S') ADVANCE(58);
      END_STATE();
    case 149:
      if (lookahead == 'S') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(149);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 150:
      if (lookahead == 'S') ADVANCE(64);
      END_STATE();
    case 151:
      if (lookahead == 'T') ADVANCE(166);
      END_STATE();
    case 152:
      if (lookahead == 'T') ADVANCE(68);
      END_STATE();
    case 153:
      if (lookahead == 'T') ADVANCE(14);
      END_STATE();
    case 154:
      if (lookahead == 'T') ADVANCE(145);
      END_STATE();
    case 155:
      if (lookahead == 'T') ADVANCE(9);
      END_STATE();
    case 156:
      if (lookahead == 'T') ADVANCE(81);
      END_STATE();
    case 157:
      if (lookahead == 'T') ADVANCE(83);
      END_STATE();
    case 158:
      if (lookahead == 'T') ADVANCE(15);
      END_STATE();
    case 159:
      if (lookahead == 'T') ADVANCE(2);
      END_STATE();
    case 160:
      if (lookahead == 'U') ADVANCE(219);
      END_STATE();
    case 161:
      if (lookahead == 'U') ADVANCE(95);
      END_STATE();
    case 162:
      if (lookahead == 'U') ADVANCE(141);
      END_STATE();
    case 163:
      if (lookahead == 'V') ADVANCE(70);
      END_STATE();
    case 164:
      if (lookahead == 'V') ADVANCE(25);
      END_STATE();
    case 165:
      if (lookahead == 'V') ADVANCE(82);
      END_STATE();
    case 166:
      if (lookahead == 'W') ADVANCE(124);
      END_STATE();
    case 167:
      if (lookahead == 'Y') ADVANCE(220);
      END_STATE();
    case 168:
      if (lookahead == 'Y') ADVANCE(217);
      END_STATE();
    case 169:
      if (lookahead == 'Y') ADVANCE(96);
      END_STATE();
    case 170:
      if (lookahead == 'a') ADVANCE(194);
      END_STATE();
    case 171:
      if (lookahead == 'a') ADVANCE(177);
      END_STATE();
    case 172:
      if (lookahead == 'd') ADVANCE(227);
      END_STATE();
    case 173:
      if (lookahead == 'e') ADVANCE(189);
      END_STATE();
    case 174:
      if (lookahead == 'e') ADVANCE(228);
      END_STATE();
    case 175:
      if (lookahead == 'e') ADVANCE(172);
      END_STATE();
    case 176:
      if (lookahead == 'f') ADVANCE(171);
      END_STATE();
    case 177:
      if (lookahead == 'i') ADVANCE(180);
      END_STATE();
    case 178:
      if (lookahead == 'l') ADVANCE(193);
      END_STATE();
    case 179:
      if (lookahead == 'l') ADVANCE(173);
      END_STATE();
    case 180:
      if (lookahead == 'l') ADVANCE(192);
      END_STATE();
    case 181:
      if (lookahead == 'n') ADVANCE(4);
      END_STATE();
    case 182:
      if (lookahead == 'n') ADVANCE(179);
      END_STATE();
    case 183:
      if (lookahead == 'o') ADVANCE(184);
      END_STATE();
    case 184:
      if (lookahead == 'p') ADVANCE(185);
      END_STATE();
    case 185:
      if (lookahead == 'p') ADVANCE(175);
      END_STATE();
    case 186:
      if (lookahead == 'r') ADVANCE(174);
      END_STATE();
    case 187:
      if (lookahead == 's') ADVANCE(226);
      END_STATE();
    case 188:
      if (lookahead == 's') ADVANCE(191);
      END_STATE();
    case 189:
      if (lookahead == 's') ADVANCE(190);
      END_STATE();
    case 190:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 191:
      if (lookahead == 't') ADVANCE(183);
      END_STATE();
    case 192:
      if (lookahead == 'u') ADVANCE(186);
      END_STATE();
    case 193:
      if (lookahead == 'w') ADVANCE(170);
      END_STATE();
    case 194:
      if (lookahead == 'y') ADVANCE(187);
      END_STATE();
    case 195:
      if (lookahead == '{') ADVANCE(202);
      END_STATE();
    case 196:
      if (lookahead == '}') ADVANCE(197);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(196);
      END_STATE();
    case 197:
      if (lookahead == '}') ADVANCE(224);
      END_STATE();
    case 198:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(198);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(232);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(229);
      END_STATE();
    case 199:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(199);
      if (lookahead != 0) ADVANCE(233);
      END_STATE();
    case 200:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 201:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(230);
      END_STATE();
    case 202:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(196);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(anon_sym_DEPLOYMENT_DASHID);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(anon_sym_VERSION_DASHID);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(anon_sym_ENVIRONMENTSECTION);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(anon_sym_SERVICESSECTION);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(anon_sym_SERVICE);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(anon_sym_SERVICE);
      if (lookahead == 'S') ADVANCE(1);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(anon_sym_END);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(anon_sym_IMAGE_DASHID);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(anon_sym_PORT_DASHMAPPING);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(anon_sym_ENV_DASHVARIABLE);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(anon_sym_COMMAND);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(anon_sym_DEPENDS_DASHON);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(anon_sym_HEALTH_DASHCHECK);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(anon_sym_RESTART_DASHPOLICY);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(anon_sym_RESOURCE_DASHLIMITS);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(anon_sym_CPU);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(anon_sym_MEMORY);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(anon_sym_VOLUME_DASHMAPPING);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(anon_sym_TO);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(anon_sym_NETWORK_DASHNAME);
      END_STATE();
    case 224:
      ACCEPT_TOKEN(sym_template_var);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(anon_sym_always);
      END_STATE();
    case 227:
      ACCEPT_TOKEN(anon_sym_unless_DASHstopped);
      END_STATE();
    case 228:
      ACCEPT_TOKEN(anon_sym_on_DASHfailure);
      END_STATE();
    case 229:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(229);
      END_STATE();
    case 230:
      ACCEPT_TOKEN(sym_version);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(230);
      END_STATE();
    case 231:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(200);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(231);
      END_STATE();
    case 232:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(232);
      END_STATE();
    case 233:
      ACCEPT_TOKEN(sym_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(233);
      END_STATE();
    case 234:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(234);
      END_STATE();
    case 235:
      ACCEPT_TOKEN(sym_empty_line);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(235);
      END_STATE();
    case 236:
      ACCEPT_TOKEN(sym_empty_line);
      if (eof) ADVANCE(203);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(235);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 236},
  [2] = {.lex_state = 236},
  [3] = {.lex_state = 236},
  [4] = {.lex_state = 236},
  [5] = {.lex_state = 236},
  [6] = {.lex_state = 236},
  [7] = {.lex_state = 236},
  [8] = {.lex_state = 236},
  [9] = {.lex_state = 236},
  [10] = {.lex_state = 236},
  [11] = {.lex_state = 236},
  [12] = {.lex_state = 236},
  [13] = {.lex_state = 236},
  [14] = {.lex_state = 236},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 198},
  [17] = {.lex_state = 198},
  [18] = {.lex_state = 199},
  [19] = {.lex_state = 149},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 198},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 198},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 198},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 149},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DEPLOYMENT_DASHID] = ACTIONS(1),
    [anon_sym_VERSION_DASHID] = ACTIONS(1),
    [anon_sym_ENVIRONMENTSECTION] = ACTIONS(1),
    [anon_sym_SERVICESSECTION] = ACTIONS(1),
    [anon_sym_SERVICE] = ACTIONS(1),
    [anon_sym_END] = ACTIONS(1),
    [anon_sym_IMAGE_DASHID] = ACTIONS(1),
    [anon_sym_PORT_DASHMAPPING] = ACTIONS(1),
    [anon_sym_ENV_DASHVARIABLE] = ACTIONS(1),
    [anon_sym_COMMAND] = ACTIONS(1),
    [anon_sym_DEPENDS_DASHON] = ACTIONS(1),
    [anon_sym_HEALTH_DASHCHECK] = ACTIONS(1),
    [anon_sym_RESTART_DASHPOLICY] = ACTIONS(1),
    [anon_sym_RESOURCE_DASHLIMITS] = ACTIONS(1),
    [anon_sym_CPU] = ACTIONS(1),
    [anon_sym_MEMORY] = ACTIONS(1),
    [anon_sym_VOLUME_DASHMAPPING] = ACTIONS(1),
    [anon_sym_TO] = ACTIONS(1),
    [anon_sym_NETWORK_DASHNAME] = ACTIONS(1),
    [sym_template_var] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [anon_sym_always] = ACTIONS(1),
    [anon_sym_unless_DASHstopped] = ACTIONS(1),
    [anon_sym_on_DASHfailure] = ACTIONS(1),
    [sym_version] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(33),
    [sym_line] = STATE(3),
    [sym_deployment_directive] = STATE(5),
    [sym_version_directive] = STATE(5),
    [sym_section_directive] = STATE(5),
    [sym_service_directive] = STATE(5),
    [sym_end_service] = STATE(5),
    [sym_service_property] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_DEPLOYMENT_DASHID] = ACTIONS(5),
    [anon_sym_VERSION_DASHID] = ACTIONS(7),
    [anon_sym_ENVIRONMENTSECTION] = ACTIONS(9),
    [anon_sym_SERVICESSECTION] = ACTIONS(9),
    [anon_sym_SERVICE] = ACTIONS(11),
    [anon_sym_END] = ACTIONS(13),
    [anon_sym_IMAGE_DASHID] = ACTIONS(15),
    [anon_sym_PORT_DASHMAPPING] = ACTIONS(17),
    [anon_sym_ENV_DASHVARIABLE] = ACTIONS(19),
    [anon_sym_COMMAND] = ACTIONS(21),
    [anon_sym_DEPENDS_DASHON] = ACTIONS(23),
    [anon_sym_HEALTH_DASHCHECK] = ACTIONS(21),
    [anon_sym_RESTART_DASHPOLICY] = ACTIONS(25),
    [anon_sym_RESOURCE_DASHLIMITS] = ACTIONS(27),
    [anon_sym_VOLUME_DASHMAPPING] = ACTIONS(29),
    [anon_sym_NETWORK_DASHNAME] = ACTIONS(23),
    [sym_comment] = ACTIONS(31),
    [sym_empty_line] = ACTIONS(33),
  },
  [STATE(2)] = {
    [sym_line] = STATE(2),
    [sym_deployment_directive] = STATE(5),
    [sym_version_directive] = STATE(5),
    [sym_section_directive] = STATE(5),
    [sym_service_directive] = STATE(5),
    [sym_end_service] = STATE(5),
    [sym_service_property] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(35),
    [anon_sym_DEPLOYMENT_DASHID] = ACTIONS(37),
    [anon_sym_VERSION_DASHID] = ACTIONS(40),
    [anon_sym_ENVIRONMENTSECTION] = ACTIONS(43),
    [anon_sym_SERVICESSECTION] = ACTIONS(43),
    [anon_sym_SERVICE] = ACTIONS(46),
    [anon_sym_END] = ACTIONS(49),
    [anon_sym_IMAGE_DASHID] = ACTIONS(52),
    [anon_sym_PORT_DASHMAPPING] = ACTIONS(55),
    [anon_sym_ENV_DASHVARIABLE] = ACTIONS(58),
    [anon_sym_COMMAND] = ACTIONS(61),
    [anon_sym_DEPENDS_DASHON] = ACTIONS(64),
    [anon_sym_HEALTH_DASHCHECK] = ACTIONS(61),
    [anon_sym_RESTART_DASHPOLICY] = ACTIONS(67),
    [anon_sym_RESOURCE_DASHLIMITS] = ACTIONS(70),
    [anon_sym_VOLUME_DASHMAPPING] = ACTIONS(73),
    [anon_sym_NETWORK_DASHNAME] = ACTIONS(64),
    [sym_comment] = ACTIONS(76),
    [sym_empty_line] = ACTIONS(79),
  },
  [STATE(3)] = {
    [sym_line] = STATE(2),
    [sym_deployment_directive] = STATE(5),
    [sym_version_directive] = STATE(5),
    [sym_section_directive] = STATE(5),
    [sym_service_directive] = STATE(5),
    [sym_end_service] = STATE(5),
    [sym_service_property] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(82),
    [anon_sym_DEPLOYMENT_DASHID] = ACTIONS(5),
    [anon_sym_VERSION_DASHID] = ACTIONS(7),
    [anon_sym_ENVIRONMENTSECTION] = ACTIONS(9),
    [anon_sym_SERVICESSECTION] = ACTIONS(9),
    [anon_sym_SERVICE] = ACTIONS(11),
    [anon_sym_END] = ACTIONS(13),
    [anon_sym_IMAGE_DASHID] = ACTIONS(15),
    [anon_sym_PORT_DASHMAPPING] = ACTIONS(17),
    [anon_sym_ENV_DASHVARIABLE] = ACTIONS(19),
    [anon_sym_COMMAND] = ACTIONS(21),
    [anon_sym_DEPENDS_DASHON] = ACTIONS(23),
    [anon_sym_HEALTH_DASHCHECK] = ACTIONS(21),
    [anon_sym_RESTART_DASHPOLICY] = ACTIONS(25),
    [anon_sym_RESOURCE_DASHLIMITS] = ACTIONS(27),
    [anon_sym_VOLUME_DASHMAPPING] = ACTIONS(29),
    [anon_sym_NETWORK_DASHNAME] = ACTIONS(23),
    [sym_comment] = ACTIONS(31),
    [sym_empty_line] = ACTIONS(33),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      sym_empty_line,
    ACTIONS(86), 17,
      anon_sym_DEPLOYMENT_DASHID,
      anon_sym_VERSION_DASHID,
      anon_sym_ENVIRONMENTSECTION,
      anon_sym_SERVICESSECTION,
      anon_sym_SERVICE,
      anon_sym_END,
      anon_sym_IMAGE_DASHID,
      anon_sym_PORT_DASHMAPPING,
      anon_sym_ENV_DASHVARIABLE,
      anon_sym_COMMAND,
      anon_sym_DEPENDS_DASHON,
      anon_sym_HEALTH_DASHCHECK,
      anon_sym_RESTART_DASHPOLICY,
      anon_sym_RESOURCE_DASHLIMITS,
      anon_sym_VOLUME_DASHMAPPING,
      anon_sym_NETWORK_DASHNAME,
      sym_comment,
  [24] = 2,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      sym_empty_line,
    ACTIONS(90), 17,
      anon_sym_DEPLOYMENT_DASHID,
      anon_sym_VERSION_DASHID,
      anon_sym_ENVIRONMENTSECTION,
      anon_sym_SERVICESSECTION,
      anon_sym_SERVICE,
      anon_sym_END,
      anon_sym_IMAGE_DASHID,
      anon_sym_PORT_DASHMAPPING,
      anon_sym_ENV_DASHVARIABLE,
      anon_sym_COMMAND,
      anon_sym_DEPENDS_DASHON,
      anon_sym_HEALTH_DASHCHECK,
      anon_sym_RESTART_DASHPOLICY,
      anon_sym_RESOURCE_DASHLIMITS,
      anon_sym_VOLUME_DASHMAPPING,
      anon_sym_NETWORK_DASHNAME,
      sym_comment,
  [48] = 2,
    ACTIONS(92), 2,
      ts_builtin_sym_end,
      sym_empty_line,
    ACTIONS(94), 17,
      anon_sym_DEPLOYMENT_DASHID,
      anon_sym_VERSION_DASHID,
      anon_sym_ENVIRONMENTSECTION,
      anon_sym_SERVICESSECTION,
      anon_sym_SERVICE,
      anon_sym_END,
      anon_sym_IMAGE_DASHID,
      anon_sym_PORT_DASHMAPPING,
      anon_sym_ENV_DASHVARIABLE,
      anon_sym_COMMAND,
      anon_sym_DEPENDS_DASHON,
      anon_sym_HEALTH_DASHCHECK,
      anon_sym_RESTART_DASHPOLICY,
      anon_sym_RESOURCE_DASHLIMITS,
      anon_sym_VOLUME_DASHMAPPING,
      anon_sym_NETWORK_DASHNAME,
      sym_comment,
  [72] = 2,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      sym_empty_line,
    ACTIONS(98), 17,
      anon_sym_DEPLOYMENT_DASHID,
      anon_sym_VERSION_DASHID,
      anon_sym_ENVIRONMENTSECTION,
      anon_sym_SERVICESSECTION,
      anon_sym_SERVICE,
      anon_sym_END,
      anon_sym_IMAGE_DASHID,
      anon_sym_PORT_DASHMAPPING,
      anon_sym_ENV_DASHVARIABLE,
      anon_sym_COMMAND,
      anon_sym_DEPENDS_DASHON,
      anon_sym_HEALTH_DASHCHECK,
      anon_sym_RESTART_DASHPOLICY,
      anon_sym_RESOURCE_DASHLIMITS,
      anon_sym_VOLUME_DASHMAPPING,
      anon_sym_NETWORK_DASHNAME,
      sym_comment,
  [96] = 2,
    ACTIONS(100), 2,
      ts_builtin_sym_end,
      sym_empty_line,
    ACTIONS(102), 17,
      anon_sym_DEPLOYMENT_DASHID,
      anon_sym_VERSION_DASHID,
      anon_sym_ENVIRONMENTSECTION,
      anon_sym_SERVICESSECTION,
      anon_sym_SERVICE,
      anon_sym_END,
      anon_sym_IMAGE_DASHID,
      anon_sym_PORT_DASHMAPPING,
      anon_sym_ENV_DASHVARIABLE,
      anon_sym_COMMAND,
      anon_sym_DEPENDS_DASHON,
      anon_sym_HEALTH_DASHCHECK,
      anon_sym_RESTART_DASHPOLICY,
      anon_sym_RESOURCE_DASHLIMITS,
      anon_sym_VOLUME_DASHMAPPING,
      anon_sym_NETWORK_DASHNAME,
      sym_comment,
  [120] = 2,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      sym_empty_line,
    ACTIONS(106), 17,
      anon_sym_DEPLOYMENT_DASHID,
      anon_sym_VERSION_DASHID,
      anon_sym_ENVIRONMENTSECTION,
      anon_sym_SERVICESSECTION,
      anon_sym_SERVICE,
      anon_sym_END,
      anon_sym_IMAGE_DASHID,
      anon_sym_PORT_DASHMAPPING,
      anon_sym_ENV_DASHVARIABLE,
      anon_sym_COMMAND,
      anon_sym_DEPENDS_DASHON,
      anon_sym_HEALTH_DASHCHECK,
      anon_sym_RESTART_DASHPOLICY,
      anon_sym_RESOURCE_DASHLIMITS,
      anon_sym_VOLUME_DASHMAPPING,
      anon_sym_NETWORK_DASHNAME,
      sym_comment,
  [144] = 2,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      sym_empty_line,
    ACTIONS(110), 17,
      anon_sym_DEPLOYMENT_DASHID,
      anon_sym_VERSION_DASHID,
      anon_sym_ENVIRONMENTSECTION,
      anon_sym_SERVICESSECTION,
      anon_sym_SERVICE,
      anon_sym_END,
      anon_sym_IMAGE_DASHID,
      anon_sym_PORT_DASHMAPPING,
      anon_sym_ENV_DASHVARIABLE,
      anon_sym_COMMAND,
      anon_sym_DEPENDS_DASHON,
      anon_sym_HEALTH_DASHCHECK,
      anon_sym_RESTART_DASHPOLICY,
      anon_sym_RESOURCE_DASHLIMITS,
      anon_sym_VOLUME_DASHMAPPING,
      anon_sym_NETWORK_DASHNAME,
      sym_comment,
  [168] = 2,
    ACTIONS(112), 2,
      ts_builtin_sym_end,
      sym_empty_line,
    ACTIONS(114), 17,
      anon_sym_DEPLOYMENT_DASHID,
      anon_sym_VERSION_DASHID,
      anon_sym_ENVIRONMENTSECTION,
      anon_sym_SERVICESSECTION,
      anon_sym_SERVICE,
      anon_sym_END,
      anon_sym_IMAGE_DASHID,
      anon_sym_PORT_DASHMAPPING,
      anon_sym_ENV_DASHVARIABLE,
      anon_sym_COMMAND,
      anon_sym_DEPENDS_DASHON,
      anon_sym_HEALTH_DASHCHECK,
      anon_sym_RESTART_DASHPOLICY,
      anon_sym_RESOURCE_DASHLIMITS,
      anon_sym_VOLUME_DASHMAPPING,
      anon_sym_NETWORK_DASHNAME,
      sym_comment,
  [192] = 2,
    ACTIONS(116), 2,
      ts_builtin_sym_end,
      sym_empty_line,
    ACTIONS(118), 17,
      anon_sym_DEPLOYMENT_DASHID,
      anon_sym_VERSION_DASHID,
      anon_sym_ENVIRONMENTSECTION,
      anon_sym_SERVICESSECTION,
      anon_sym_SERVICE,
      anon_sym_END,
      anon_sym_IMAGE_DASHID,
      anon_sym_PORT_DASHMAPPING,
      anon_sym_ENV_DASHVARIABLE,
      anon_sym_COMMAND,
      anon_sym_DEPENDS_DASHON,
      anon_sym_HEALTH_DASHCHECK,
      anon_sym_RESTART_DASHPOLICY,
      anon_sym_RESOURCE_DASHLIMITS,
      anon_sym_VOLUME_DASHMAPPING,
      anon_sym_NETWORK_DASHNAME,
      sym_comment,
  [216] = 2,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      sym_empty_line,
    ACTIONS(122), 17,
      anon_sym_DEPLOYMENT_DASHID,
      anon_sym_VERSION_DASHID,
      anon_sym_ENVIRONMENTSECTION,
      anon_sym_SERVICESSECTION,
      anon_sym_SERVICE,
      anon_sym_END,
      anon_sym_IMAGE_DASHID,
      anon_sym_PORT_DASHMAPPING,
      anon_sym_ENV_DASHVARIABLE,
      anon_sym_COMMAND,
      anon_sym_DEPENDS_DASHON,
      anon_sym_HEALTH_DASHCHECK,
      anon_sym_RESTART_DASHPOLICY,
      anon_sym_RESOURCE_DASHLIMITS,
      anon_sym_VOLUME_DASHMAPPING,
      anon_sym_NETWORK_DASHNAME,
      sym_comment,
  [240] = 2,
    ACTIONS(124), 2,
      ts_builtin_sym_end,
      sym_empty_line,
    ACTIONS(126), 17,
      anon_sym_DEPLOYMENT_DASHID,
      anon_sym_VERSION_DASHID,
      anon_sym_ENVIRONMENTSECTION,
      anon_sym_SERVICESSECTION,
      anon_sym_SERVICE,
      anon_sym_END,
      anon_sym_IMAGE_DASHID,
      anon_sym_PORT_DASHMAPPING,
      anon_sym_ENV_DASHVARIABLE,
      anon_sym_COMMAND,
      anon_sym_DEPENDS_DASHON,
      anon_sym_HEALTH_DASHCHECK,
      anon_sym_RESTART_DASHPOLICY,
      anon_sym_RESOURCE_DASHLIMITS,
      anon_sym_VOLUME_DASHMAPPING,
      anon_sym_NETWORK_DASHNAME,
      sym_comment,
  [264] = 2,
    STATE(10), 1,
      sym_restart_policy,
    ACTIONS(128), 3,
      anon_sym_always,
      anon_sym_unless_DASHstopped,
      anon_sym_on_DASHfailure,
  [273] = 2,
    ACTIONS(130), 1,
      sym_number,
    STATE(10), 1,
      sym_port_mapping,
  [280] = 1,
    ACTIONS(132), 1,
      sym_number,
  [284] = 1,
    ACTIONS(134), 1,
      sym_value,
  [288] = 1,
    ACTIONS(136), 1,
      sym_version,
  [292] = 1,
    ACTIONS(134), 1,
      sym_template_var,
  [296] = 1,
    ACTIONS(134), 1,
      sym_quoted_string,
  [300] = 1,
    ACTIONS(134), 1,
      sym_identifier,
  [304] = 1,
    ACTIONS(138), 1,
      anon_sym_TO,
  [308] = 1,
    ACTIONS(140), 1,
      sym_identifier,
  [312] = 1,
    ACTIONS(142), 1,
      sym_quoted_string,
  [316] = 1,
    ACTIONS(144), 1,
      anon_sym_TO,
  [320] = 1,
    ACTIONS(146), 1,
      anon_sym_CPU,
  [324] = 1,
    ACTIONS(148), 1,
      sym_quoted_string,
  [328] = 1,
    ACTIONS(150), 1,
      anon_sym_MEMORY,
  [332] = 1,
    ACTIONS(152), 1,
      sym_quoted_string,
  [336] = 1,
    ACTIONS(154), 1,
      sym_identifier,
  [340] = 1,
    ACTIONS(156), 1,
      sym_quoted_string,
  [344] = 1,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
  [348] = 1,
    ACTIONS(160), 1,
      anon_sym_SERVICE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 24,
  [SMALL_STATE(6)] = 48,
  [SMALL_STATE(7)] = 72,
  [SMALL_STATE(8)] = 96,
  [SMALL_STATE(9)] = 120,
  [SMALL_STATE(10)] = 144,
  [SMALL_STATE(11)] = 168,
  [SMALL_STATE(12)] = 192,
  [SMALL_STATE(13)] = 216,
  [SMALL_STATE(14)] = 240,
  [SMALL_STATE(15)] = 264,
  [SMALL_STATE(16)] = 273,
  [SMALL_STATE(17)] = 280,
  [SMALL_STATE(18)] = 284,
  [SMALL_STATE(19)] = 288,
  [SMALL_STATE(20)] = 292,
  [SMALL_STATE(21)] = 296,
  [SMALL_STATE(22)] = 300,
  [SMALL_STATE(23)] = 304,
  [SMALL_STATE(24)] = 308,
  [SMALL_STATE(25)] = 312,
  [SMALL_STATE(26)] = 316,
  [SMALL_STATE(27)] = 320,
  [SMALL_STATE(28)] = 324,
  [SMALL_STATE(29)] = 328,
  [SMALL_STATE(30)] = 332,
  [SMALL_STATE(31)] = 336,
  [SMALL_STATE(32)] = 340,
  [SMALL_STATE(33)] = 344,
  [SMALL_STATE(34)] = 348,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_directive, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_directive, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_service, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_service, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_deployment_directive, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_deployment_directive, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_directive, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_service_directive, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_version_directive, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_version_directive, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_property, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_service_property, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_restart_policy, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_restart_policy, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_port_mapping, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_port_mapping, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_property, 4, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_service_property, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_service_property, 5, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_service_property, 5, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [158] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_athena(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "athena",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
